@startuml
title "量潮应用系统架构设计"

package "代码DevOps" {
    package "代码仓库" {
        folder "服务端代码" as code

    }
    package "流水线" {
        component "CloudBase Framework" as tcb_cli
        code -- tcb_cli
    }
}

package "服务网格" {
    package "应用层" {
        cloud "课堂服务" as qtclass
    }
    package "领域层" {
        cloud "用户服务" as qtuser
    }
    qtclass -- qtuser
    tcb_cli -right-> qtclass
    tcb_cli --> qtuser
}

package "数据库和存储" {
    database "腾讯云TDSQL-C MySQL版" as mysql
    qtclass -- mysql
    qtuser -- mysql
    storage "腾讯云对象存储" as storage
    qtclass -- storage
}

package "业务资源DevOps" {
    package "课程资源代码仓库" {
        folder "教程" as tutorial
    }
    package "课程资源上线流水线" {
        component "命令行工具" as qtclass_admin_cli
        tutorial --> qtclass_admin_cli
        qtclass_admin_cli -left-> qtclass
    } 
}

@enduml